# Generated by Django 2.2.3 on 2019-09-26 22:04

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='text',
            field=wagtail.core.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
