version: '2'

volumes:
  postgres_data_dev: {}
  webpack_node_modules: {}

services:
  postgres:
    container_name: sharpertool-postgres
    build: ./compose/postgres
    volumes:
      # You can also modify this to point to your local Dropbox location where the shared
      # backups are stored. For me this is:
      - "~/Dropbox (Personal)/Development/database/sharpertool:/backups"
      - ./database/backups:/local_backups
    environment:
      - POSTGRES_USER=django_user
      - POSTGRES_DB=sharpertool
    ports:
      - "5446:5432"

  smtpd:
    container_name: sharpertool-smtpd
    build: ./compose/smtpd
    ports:
      - "8046:25"

