#!/bin/sh

port=${1:-8000}

base=$(cd $(dirname $0);pwd)
root=$(dirname $(find . -depth 2 -name 'manage.py'))
cd ${root}

pluscheck=$(${base}/.venv3/bin/python manage.py | grep runserver_plus)
runcmd=${pluscheck:-runserver}
echo "Run command: ${runcmd}"

while true
do
    ${base}/.venv3/bin/python manage.py ${runcmd} ${port}
    sleep 2
done


