# Generated by Django 2.0.7 on 2018-07-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resumepage_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumepage',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='resumepage',
            name='dob',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='resumepage',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='resumepage',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='resumepage',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
