# Generated by Django 2.0.7 on 2018-07-09 02:06

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20180709_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumepage',
            name='heading',
            field=wagtail.core.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='resumepage',
            name='intro',
            field=wagtail.core.fields.RichTextField(default=''),
        ),
    ]
