# Generated by Django 2.0.7 on 2018-07-09 02:23

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20180709_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumepage',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='resumepage',
            name='contact_info',
            field=wagtail.core.fields.RichTextField(default=''),
        ),
    ]
