# Generated by Django 2.0.7 on 2018-07-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20180709_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumepage',
            name='contact_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumepage',
            name='contact_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
