# Generated by Django 2.0.7 on 2018-07-09 03:11

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0020_add-verbose-name'),
        ('resume', '0006_auto_20180709_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeProjectItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('section', models.CharField(blank=True, choices=[('webdesign', 'Web Design'), ('engineering', 'Engineering'), ('edatools', 'EDA Tools')], max_length=20, null=True)),
                ('title', models.CharField(max_length=40)),
                ('subtext', models.CharField(blank=True, max_length=80, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_item', to='resume.ResumePage')),
                ('thumb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
