# Generated by Django 2.0.7 on 2018-07-09 22:56

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_resumeblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='details',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
