# Generated by Django 5.2.14 on 2026-05-10 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_skills_details'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumepage',
            name='resume_pdf',
            field=models.ForeignKey(blank=True, help_text='Optional: upload a PDF version for download.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
    ]
