# Generated by Django 2.2.3 on 2019-09-26 22:10

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_serviceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='text2',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
