# Generated by Django 2.2.3 on 2019-09-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20190926_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
