# Generated by Django 2.2.3 on 2019-09-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepagehighlight_graphic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagehighlight',
            name='graphic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
